export function captureException(file: string, ...msg: Array<string>) {
  console.error(file, msg)
}
